# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

# config file for demo site, DELETE IT IF YOU WANT.


## => Site Settings
##############################
text_skin: default # "default" (default), "dark", "forest", "ocean", "chocolate", "orange"
highlight_theme: default # "default" (default), "tomorrow", "tomorrow-night", "tomorrow-night-eighties", "tomorrow-night-blue", "tomorrow-night-bright"
url     : https://weigao.cc
baseurl : ""
title   : weigao.cc
description: >
      welcome and thxs for visiting!
  # A customizable Jekyll theme for blog or site


## => Language and Timezone
##############################
lang: en # the language of your site, "en" (default, English), "zh"(简体中文), "zh-Hans"(简体中文), "zh-Hant"(繁體中文)
timezone: Asia/Shanghai


## => Author and Social
##############################
author:
  type      : person # "person" (default), "organization"
  name      : weigao chen
  url       : /about.html
  avatar    : /assets/author.png
  bio: > 
        student in xidian university; a coder;
  email     : mail@weigao.cc
  facebook  : 
  twitter   : 
  github    : chenweigao
  linkedin  :
  googleplus: 
  weibo     : 5619519158
  douban    :


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: chenweigao/chenweigao.github.io
repository_tree: master


## => Paths
##############################
paths:
  root    /: # title link url, "/" (default)
  home    home.html : # home layout url, "/" (default)
  archive : # "/archive.html" (default)
  rss     : # "/feed.xml" (default)


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->
excerpt_type: html # text (default), html

## license
# license: CC-BY-4.0 # "CC-BY-4.0", "CC-BY-SA-4.0", "CC-BY-NC-4.0", "CC-BY-ND-4.0"

## TOC
toc:
  selectors: # "h1,h2,h3" (default)


## => Markdown Enhancements
##############################
## Mathjax
mathjax: false # false (default), true
mathjax_autoNumber: false # false (default), true

## Mermaid
mermaid: false # false (default), true

## Chart
chart: false # false (default), true


## => Paginate
##############################
paginate: 8
paginate_path: /blog/page:num # don't change this unless for special need


## => Sources
##############################
sources: # bootcdn (default), unpkg


## => Comments
##############################
# comments:
#   provider: gitalk # false (default), "disqus", "gitalk", "custom"

  ## Disqus
  # disqus:
  #   shortname: # the Disqus shortname for the site

  ## Gitalk
  # please refer to https://github.com/gitalk/gitalk for more info.
  # gitalk:
  #   clientID    : 6cef80132492d89a6adb
  #   clientSecret: 4d7577147a7f7afca21a9e28b61b087c94989b2c
  #   repository  : nerche_talk
  #   owner       : chenweigao
  #   admin:
  #     - chenweigao


## => Pageview
##############################
# pageview:
#   provider: leancloud # false (default), "leancloud", "custom"

#   ## Leancloud
#   leancloud:
#     app_id    : wJrq8Ck2MqeaFzOYUf0TcP6G-gzGzoHsz
#     app_key   : taRHm1fEce4nGp2lmNgkiW9U
#     app_class : note


## => Analytics
##############################
# analytics:
#   provider: # false (default), "google", "custom"

  ## Google Analytics
  # google:
  #   tracking_id : UA-71907556-1
  #   anonymize_ip: false


## => Build
##############################
markdown    : kramdown
# highlighter : rough
permalink   : date
# kramdown:
#   input: GFM
exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor
  - /_posts
  - /index.html

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      # license: true
      aside:
        toc: true
      show_edit_on_github: true
      pageview: true
      show_author_profile: true
      mathjax: false
      mathjax_autoNumber: false
      author: weigao chen

  - scope:
      path: "docs/en"
    values:
      layout: page
      sidebar:
        nav: docs-en
      # license: true
      aside:
        toc: false
      show_edit_on_github: true
      # show_author_profile: true
  - scope:
      path: "docs/zh"
    values:
      layout: page
      sidebar:
        nav: docs-zh
      license: false
      aside:
        toc: true
      lang: en
      show_edit_on_github: false


## => Plugins
##############################
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-github-metadata
  - jemoji

data_dir: /docs/_data
